on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: BETA
    steps:
      - uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@dcoutinho96'

      - run: node -v

      - run: echo "@dcoutinho96:registry=https://npm.pkg.github.com" > .npmrc

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Unit Tests
        run: npm run test:unit
        env:
          VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL: ${{ vars.VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL }}
          NODE_ENV: test
          CI: true

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: npx start-server-and-test dev http://localhost:5173 test:e2e
        env:
          VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL: ${{ vars.VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL }}
          NODE_ENV: test
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: test
    environment: BETA
    steps:
      - uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@dcoutinho96'

      - run: node -v

      - run: echo "@dcoutinho96:registry=https://npm.pkg.github.com" > .npmrc

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm run build
        env:
          VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL: ${{ vars.VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL }}
          ENV: BETA
          NODE_ENV: production
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: BETA
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -sS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
