on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: BETA
    steps:
      - uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@dcoutinho96'

      - name: Show Node version
        run: node -v

      - name: Point scope to GitHub Packages
        run: echo "@dcoutinho96:registry=https://npm.pkg.github.com" > .npmrc

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Unit & E2E Tests
        run: npm run test -- --run
        env:
          VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL: ${{ vars.VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL }}
          NODE_ENV: test
          CI: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test   
    environment: BETA
    steps:
      - uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@dcoutinho96'

      - name: Show Node version
        run: node -v

      - name: Point scope to GitHub Packages
        run: echo "@dcoutinho96:registry=https://npm.pkg.github.com" > .npmrc

      - name: Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: npm run build
        env:
          VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL: ${{ vars.VITE_SPOTIFY_CLONE_LUIZALABS_API_BASE_URL }}
          ENV: BETA
          NODE_ENV: production
          CI: true

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build
